POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi
SPLIT_POINTING_ENABLE = yes

QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += st7789_spi
BACKLIGHT_ENABLE = yes
BACKLIGHT_DRIVER = software    

CONSOLE_ENABLE = yes
