// Copyright 2026 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter-convert-font-image` with arguments:
//    format         | mono4
//    unicode_glyphs | 
//    output         | generated
//    input          | arial.png

#pragma once

#include <qp.h>

extern const uint32_t font_arial_length;
extern const uint8_t  font_arial[2885];
