SPLIT_POINTING_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi

QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += st7789_spi
QUANTUM_PAINTER_LVGL_INTEGRATION = yes

BACKLIGHT_ENABLE = yes
BACKLIGHT_DRIVER = pwm

CONSOLE_ENABLE = yes

SRC += lvgl_helpers.c \
	   display.c