SPLIT_POINTING_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3389

QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += st7789_spi
QUANTUM_PAINTER_LVGL_INTEGRATION = yes

CONSOLE_ENABLE = yes
WPM_ENABLE = yes
SPLIT_WPM_ENABLE = yes

MOUSEKEY_ENABLE = yes

SRC += lvgl_helpers.c \
	   display.c